name: Lint JS
on: [push, pull_request]
jobs:
  standardjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npx standard
